### ISSUE TITLE
Correção ortográfica

### ISSUE THREAD

**Issue by glauberlpc** [edusantana/introducao-a-computacao-livro#24]
Versão 1.0.5 pág 1 na parte de objetivos do Capitulo 1 no item 2 a palavra tecnologias falta um "o".

**Comment by edusantana** [comment]
Obrigado @glauberlpc pela indicação, você pode verificar a correção em: 1f50b6becaae20223ef1cf2c77c88aba6e945988

Esta correção só estará disponível ao público na próxima versão do livro. Vou verificar os demais capítulos em busca de erros ortográficos.

**Comment by edusantana** [comment]
Estou utilizando este issue para registrar outras correções ortográficas realizadas no livro inteiro.
