### ISSUE TITLE
Mencionarmos escrito errado

### ISSUE THREAD

**Issue by Tomiellodutra** [edusantana/introducao-a-computacao-livro#28]
Capitulo 1.
Página 1/108 (na nota da página).
A palavra mencionarmos está escrita da seguinte forma "mencinarmos".

**Comment by edusantana** [comment]
Obrigado @Tomiellodutra por sua contribuição. Mas esse trecho já havia sido [corrigido antes](https://github.com/ufpb-computacao/introducao-a-computacao-livro/commit/1f50b6becaae20223ef1cf2c77c88aba6e945988#diff-731a740cb781900a03e7e09e9a515eceL37).
