### ISSUE TITLE
"idéia básica" escrita errado

### ISSUE THREAD

**Issue by Tomiellodutra** [edusantana/introducao-a-computacao-livro#29]
No capitulo 1.
na página 3/108.
Está escrito "ideia basico", pela concordância, ficaria melhor se fosse "idéia basica".

**Comment by edusantana** [comment]
@Tomiellodutra este item [já foi corrigido anteriormente neste commit](https://github.com/ufpb-computacao/introducao-a-computacao-livro/commit/0d5c0b109a322afa78394047aa0c356f2cdef291#diff-731a740cb781900a03e7e09e9a515eceL92).

Se você estiver lendo uma versão digital, considere [utilizar a última versão lançada](https://github.com/ufpb-computacao/introducao-a-computacao-livro/releases/download/v1.1.2/introducao-a-computacao-livro-v1.1.2.pdf).

Obrigado por suas contribuições.
